high_ui/urls.py
from django.urls import path

from .views import PlayView
from .views import HomeView

app_name = "high_ui"

urlpatterns = [
    path(r"", HomeView.as_view(), name="splash"),
    path(r"play/", PlayView.as_view(), name="play"),
]

zanimo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("high_ui.urls", namespace="high_ui")),
]

high_ui/models.py
from django.db import models

# Create your models here.

high_ui/views.py
from random import randrange
from random import choice
from random import shuffle

from django.views.generic.base import TemplateView


SELECTION = 15

COLORS = ("orange", "brown", "red", "grey", "pink", "blue")
SIZE = ("small", "tall")
DIRECTION = ("right", "left")

CARAC = {
    "skin": (
        (COLORS[0], "orange_fr.mp3", "Trouve l'écureuil orange."),
        (COLORS[1], "brown_fr.mp3", "Trouve l'écureuil brun."),
        (COLORS[2], "red_fr.mp3", "Trouve l'écureuil rouge."),
        (COLORS[3], "grey_fr.mp3", "Trouve l'écureuil gris."),
    ),
    "height": (
        (SIZE[0], "small_fr.mp3", "Trouve le petit écureuil."),
        (SIZE[1], "tall_fr.mp3", "Hé hé hé, trouve le grand écureuil."),
    ),
    "orientation": (
        (DIRECTION[0], "turn_right_fr.mp3", "Trouve l'écureuil tourné à droite."),
        (DIRECTION[1], "left_fr.mp3", "Hé vas-y, trouve l'écureuil tourné à gauche."),
    ),
    "teeth": (
        (SIZE[0], "small_teeth_fr.mp3", "Trouve l'écureuil avec des petites dents."),
        (SIZE[1], "tall_teeth_fr.mp3", "Trouve l'écureuil avec de grandes dents."),
    ),
    "nose": (
        (COLORS[4], "pink_nose_fr.mp3", "Vas-y, trouve l'écureuil avec le nez rose."),
        (COLORS[5], "blue_nose_fr.mp3", "Trouve l'écureuil avec le nez bleu."),
    ),
}

SQUIRRELS = [
    {"skin": COLORS[0], "height": SIZE[1], "orientation": DIRECTION[0], "teeth": SIZE[1], "nose": COLORS[4]},
    {"skin": COLORS[1], "height": SIZE[1], "orientation": DIRECTION[0], "teeth": SIZE[1], "nose": COLORS[4]},
    {"skin": COLORS[2], "height": SIZE[1], "orientation": DIRECTION[0], "teeth": SIZE[1], "nose": COLORS[4]},
    {"skin": COLORS[3], "height": SIZE[1], "orientation": DIRECTION[0], "teeth": SIZE[1], "nose": COLORS[4]},
    {"skin": COLORS[0], "height": SIZE[1], "orientation": DIRECTION[1], "teeth": SIZE[1], "nose": COLORS[4]},
    {"skin": COLORS[1], "height": SIZE[1], "orientation": DIRECTION[1], "teeth": SIZE[1], "nose": COLORS[4]},
    {"skin": COLORS[2], "height": SIZE[1], "orientation": DIRECTION[1], "teeth": SIZE[1], "nose": COLORS[4]},
    {"skin": COLORS[3], "height": SIZE[1], "orientation": DIRECTION[1], "teeth": SIZE[1], "nose": COLORS[4]},
    {"skin": COLORS[0], "height": SIZE[0], "orientation": DIRECTION[0], "teeth": SIZE[1], "nose": COLORS[4]},
    {"skin": COLORS[1], "height": SIZE[0], "orientation": DIRECTION[0], "teeth": SIZE[1], "nose": COLORS[4]},
    {"skin": COLORS[2], "height": SIZE[0], "orientation": DIRECTION[0], "teeth": SIZE[1], "nose": COLORS[4]},
    {"skin": COLORS[3], "height": SIZE[0], "orientation": DIRECTION[0], "teeth": SIZE[1], "nose": COLORS[4]},
    {"skin": COLORS[0], "height": SIZE[1], "orientation": DIRECTION[0], "teeth": SIZE[1], "nose": COLORS[5]},
    {"skin": COLORS[0], "height": SIZE[1], "orientation": DIRECTION[0], "teeth": SIZE[0], "nose": COLORS[4]},
    {"skin": COLORS[1], "height": SIZE[1], "orientation": DIRECTION[0], "teeth": SIZE[0], "nose": COLORS[4]},
    {"skin": COLORS[2], "height": SIZE[1], "orientation": DIRECTION[0], "teeth": SIZE[0], "nose": COLORS[4]},
    {"skin": COLORS[3], "height": SIZE[1], "orientation": DIRECTION[0], "teeth": SIZE[0], "nose": COLORS[4]},
]

FORREST_NB = 6


class HomeView(TemplateView):
    template_name = "high_ui/splash.html"


class PlayView(TemplateView):
    template_name = "high_ui/play.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["animals_sprites_size"] = len(SQUIRRELS)*100
        context["forrest_sprites_size"] = FORREST_NB*100
        
        selected_carac_type = choice(list(CARAC))
        selected_carac = randrange(0, len(CARAC[selected_carac_type]), 1)
        context["instruction"] = CARAC[selected_carac_type][selected_carac][2]
        context["instruction_sound"] = CARAC[selected_carac_type][selected_carac][1]

        winner_number = randrange(0, len(SQUIRRELS), 1)
        while SQUIRRELS[winner_number][selected_carac_type] != CARAC[selected_carac_type][selected_carac][0]:
            winner_number = randrange(0, len(SQUIRRELS), 1)

        winner_animal = {
            "winner": True,
            "offset": (len(SQUIRRELS) - winner_number)*100
        }
        context["elements"] = []
        context["elements"].append(winner_animal)

        allowed_squirrels = []

        for i, squirrel in enumerate(SQUIRRELS):
            if squirrel[selected_carac_type] != CARAC[selected_carac_type][selected_carac][0]:
                allowed_squirrels.append(i)

        forrest_elements_nb = randrange(0, SELECTION//2, 1)
        for i in range(1, SELECTION - forrest_elements_nb):
            loser_number = randrange(0, len(allowed_squirrels), 1)

            loser_animal = {
                "winner": False,
                "offset": (len(SQUIRRELS) - allowed_squirrels[loser_number])*100
            }
            context["elements"].append(loser_animal)

        for i in range(0, forrest_elements_nb):
            plant = {
                "winner": None,
                "offset": (FORREST_NB - randrange(0, FORREST_NB, 1))*100
            }
            context["elements"].append(plant)

        shuffle(context["elements"])

        print(context)
        return context

high_ui/templates/high_ui/play.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Mirettes : trouve l'animal demandé :)</title>
    {% include 'high_ui/style.html' %}
<style>
@keyframes jump {
  from {
    margin-top: 2em;
  }

  to {
    margin-top: 0em;
  }
}

.under {
    z-index: -1;
    position: absolute;
    margin-top: 2em;
}

.over {
    z-index: -1;
    position: absolute;
    animation-duration: 0.1s;
    animation-name: jump;
    animation-iteration-count: infinite;
    animation-direction: alternate;
    margin-top: 2em;
}

.left {
    left: 0;
    margin-left: 2em;
}

.right {
    right: 0;
    margin-right: 2em;
}

#happies_squirrels {
    width: 100%;
}

</style>
</head>

<body>

<div id="text">
    <div><h1>{{instruction}}</h1></div>
    <div id="fail" class="hidden"><h1>Oups... ce n'est pas ça ! :)</h1></div>
</div>
<div id="selection" class="flex-container">
{% for element in elements %}
    {% if element.winner == None %}
        <div class="forrest" style="background-size: {{ forrest_sprites_size }}%; background-position: {{ element.offset }}% 0;"></div>
    {% else %}
        <div class="animal" onclick={% if element.winner %}won(){% else %}lost(){% endif %} style="background-size: {{ animals_sprites_size }}%; background-position: {{ element.offset }}% 0;"></div>
    {% endif %}
{% endfor %}
</div>
<div id="won" class="hidden">
    <div><h1>Bravo ! Tu as trouvé !!</h1></div>
    <div><button class='button' onclick="location.reload();">Rejouer</button></div>
    <div id="happies_squirrels">
        <img src='{% static "won_shadow2.png" %}' width="20%" height="auto" class="under left" />
        <img src='{% static "won_squirrel2.png" %}' width="20%" height="auto" class="over left" />
        <img src='{% static "won_shadow3.png" %}' width="20%" height="auto" class="under left" />
        <img src='{% static "won_squirrel3.png" %}' width="20%" height="auto" class="over left" />
    </div>
    <div>
        <img src='{% static "won_shadow1.png" %}' width="20%" height="auto" class="under right" />
        <img src='{% static "won_squirrel1.png" %}' width="20%" height="auto" class="over right" />
    </div>
</div>
<div id="footer"></div>

<script>
    function won(elemID) {
        var yeah = new Audio('{% static "win.mp3" %}');
        yeah.play();
        document.getElementById("fail").classList.add('hidden');
        document.getElementById("selection").classList.add('hidden');
        document.getElementById("won").classList.remove('hidden');
    }

    function lost(elemID) {
        var fail = new Audio('{% static "fail.mp3" %}');
        fail.play();
        document.getElementById("fail").classList.remove('hidden');
    }

    function getRandomInt() {
        return Math.floor(Math.random() * Math.floor(3));
    }

    // bug, a squirrel can be isolate in an other row hidden by the bushes
    /*
    var elements = document.querySelectorAll('.animal');
    for (var i = 0; i < elements.length; i++) {
            elements[i].style.marginLeft = getRandomInt() + "em";
            elements[i].style.marginRight = getRandomInt() + "em";
            elements[i].style.marginBottom = getRandomInt() + "em";
    }
    */

    let forrest = new Audio('{% static "forrest.mp3" %}');
    forrest.loop = true;
    forrest.play();

    var instruction = new Audio('{% static instruction_sound %}');
    instruction.play();
</script>

</body>
</html>

high_ui/templates/high_ui/splash.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Mirettes : trouve l'animal demandé :)</title>
    {% include 'high_ui/style.html' %}
</head>

<body>

<div id='title'>
    <div><img src="{% static "title.png" %}" alt="splash title" width="80%"/></div>
    <div><button class='button' onclick="window.open('{% url 'high_ui:play' %}','_self')">Jouer</button></div>
</div>
<div id="footer">

<script>
    let forrest = new Audio('{% static "forrest.mp3" %}');
    forrest.loop = true;
    forrest.play();

    var instruction = new Audio('{% static instruction_sound %}');
    instruction.play();
</script>

</body>
</html>

high_ui/templates/high_ui/style.html
{% load static %}
<style>
@font-face {
  font-family: 'Gloria Hallelujah';
  src: url('{% static "gloria_hallelujah.woff2" %}');
}

html, body {
    width:100%;
    background-color: #C9DBB8;
    font-family: 'Gloria Hallelujah', cursive;
}

* {
padding:0;
margin:0;
}

.hidden {
    display: none;
}

#footer {
    display: block;
    bottom: 0;
    height: 8em;
    width: 100%;
    position: fixed;
    background-image: url('{% static "forrest_footer.png" %}');
    background-repeat: repeat;
    background-size: auto 8em;
}

/* SPLASH */
#title {
    text-align: center;
    display: block;
    width: 60%;
    height: 30em;
    margin: 2em auto;
}

.button:active {
    background: linear-gradient(#705819, #b08b28);
}

.button {
    font-family: 'Gloria Hallelujah', cursive;
    background: linear-gradient(#b08b28, #705819);
    border: none;
    border-radius: 1em;
    color: white;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 1.5em;
    margin: 0.5em;
    padding: 0.5em 1em;
}

/* SPLASH - end */

/* PLAY */
.flex-container {
    display: flex;
    flex-wrap: wrap;
    width: 80%;
    bottom: 0;
    margin-left: auto;
    margin-right: auto;
    text-align: center;
}

.flex-container > div {
    width: 15%;
    height: 0;
    padding-bottom: 15%;
    display: flex;
}

.animal {
    background-image: url('{% static "squirrel.png" %}');
}

.forrest {
    background-image: url('{% static "forrest.png" %}');
}

.hidden {
    display: none;
}

#text {
    width: 100%;
    height: 8em;
    text-align: center;
}

#text > div {
    height: 3em;
    margin: 1em;
}

#won > div > h1 {
    font-size: 4em;
    text-align: center;
}

#won > div {
    text-align: center;
}

/* PLAY - end */
</style>